# Netlify NÃO É RECOMENDADO para aplicações Flask!
# Netlify é para sites estáticos, não aplicações backend Python.
# 
# Use Render.com ou PythonAnywhere para aplicações Flask.
# 
# Se mesmo assim quiser tentar:
# Netlify Functions não suporta Flask diretamente.

[build]
  publish = "static"
  command = "echo 'Netlify não suporta Flask. Use Render.com ou PythonAnywhere'"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

